# Generated by Django 5.0.1 on 2024-01-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('TD', 'Todo'), ('IN', 'In Progress'), ('CD', 'Completed')], default=('TD', 'Todo'), max_length=2),
        ),
    ]
