# Generated by Django 5.0.1 on 2024-01-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('TD', 'To Do'), ('IN', 'In Progress'), ('CD', 'Completed')], default='To Do', max_length=11),
        ),
    ]
